In [1]:
import numpy as np

C=np.random.randint(-10,10,(4,4))
A=np.dot(C.T,C)
print(A)#生成正定对称矩阵

vals,vecs=np.linalg.eig(A)
print(vals)
print(vecs)#返回

[[ 71  39 120 -21]
 [ 39 149  25  53]
 [120  25 251 -98]
 [-21  53 -98 226]]
[375.01196148 226.84205474   5.73203208  89.4139517 ]
[[ 0.34165906  0.30620264 -0.87887255  0.13073662]
 [ 0.01560502  0.66570031  0.12868282 -0.73487435]
 [ 0.76499903  0.28911355  0.45124888  0.35716143]
 [-0.54571243  0.61603279  0.08601286  0.56151877]]


In [2]:
x=np.dot(A,vecs[:,0])
y=np.dot(vals[0],vecs[:,0])
print(x,"\n",y)#验证Ax=λx

[ 128.12623343    5.85206772  286.88378706 -204.64868821] 
 [ 128.12623343    5.85206772  286.88378706 -204.64868821]


In [ ]:
Lambda=np.diag(vals)
x=numpy.linalg.inv(vecs)
B=np.dot(np.dot(vecs,Lambda),x)
print(B)