# NumPy Basics: Arrays and Vectorized Computation
# Numpy 基础：数组和向量计算

* Numpy，是 Numerical Pythn 的简称，它是目前 Python 数值计算中最为重要的基础包。大多数计算包都提供了基于 Numpy 的科学函数功能，将 Numpy 的数组对象作为数据交换的通用语。
* ndarray,一种高效多维数组
* 对所有数据进行快速的矩阵计算，而无需编写循环程序。
* 线性代数、随机数生成以及傅里叶变换功能。

In [2]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [ ]:
import numpy as np
# 使用 numpy 生成 100W 个数据
my_arr = np.arange(1000000)
# 使用 range 函数生成 100W 个数据
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2 # 执行时间计算
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] # 执行时间计算

## The NumPy ndarray: A Multidimensional Array Object

## Numpy ndarray：多维数组对象

In [ ]:
import numpy as np
# Generate some random data
# 生成随机数，2*3 个
data = np.random.randn(2, 3)
data

In [ ]:
data * 10
data + data

In [ ]:
data.shape
data.dtype

### Creating ndarrays
### 创建 ndarray

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

In [ ]:
arr2.ndim
arr2.shape

In [ ]:
arr1.dtype
arr2.dtype

In [ ]:
np.zeros(10) # 一次性创造全 0 数组
np.zeros((3, 6)) # 一次性创建全 1 数组
np.empty((2, 3, 2)) # empty 可以创建一个没有初始化数值的数组。

In [ ]:
np.arange(15) # Python 内置函数 range 的数组版

### Data Types for ndarrays
### ndarray 数据类型

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # float64 类型，值为[1,2,3]
arr2 = np.array([1, 2, 3], dtype=np.int32)   # int32   类型，值为[1,2,3]
arr1.dtype
arr2.dtype

In [ ]:
arr = np.array([1, 2, 3, 4, 5])    # 使用 [1,2,3,4,5] 生成一个数组
print(arr.dtype)                   # 输出数据类型
float_arr = arr.astype(np.float64) # 转成 float64 类型
float_arr.dtype                    # 输出数据类型

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])  # 使用[3.7, -1.2, -2.6, 0.5, 12.9, 10.1]生成 ndarray
print(arr)

print(arr.astype(np.int32)) # 转成 int32 类型

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_) # 生成 string 类型的 ndarray
print(numeric_strings)
print(numeric_strings.astype(float))

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

In [ ]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

### Arithmetic with NumPy Arrays
### Numpy 数组算术

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
1 / arr

In [ ]:
arr ** 0.5

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [ ]:
arr2

In [ ]:
arr2 > arr

### Basic Indexing and Slicing
### 基础索引和切片

In [ ]:
arr = np.arange(10)

In [ ]:
arr

In [ ]:
arr[5]

In [ ]:
arr[5:8]

In [ ]:
arr[5:8] = 12 # 数值被传递给了整个切片

In [ ]:
arr

In [ ]:
arr_slice = arr[5:8] # 从 5 到 8 取 3 个

In [ ]:
arr_slice

In [ ]:
arr_slice[1] = 12345 # 给切片[1]赋值

In [ ]:
arr

In [ ]:
arr_slice[:] = 64 # 给切片整个赋值

In [ ]:
arr 

![](http://ww2.sinaimg.cn/large/006y8mN6ly1g6aptyi99vj30gk0ekaf5.jpg)

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr2d[2]

In [ ]:
arr2d[0][2]

In [ ]:
arr2d[0, 2]

### 在多维数组中，你可以省略后续索引值，返回的对象将是降低一个维度的数组。因此在一个 2X2X3 的数组 arr3d 中：

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
arr3d

In [ ]:
arr3d.dtype

In [ ]:
arr3d.ndim

In [ ]:
arr3d[0] # arr3d[0] 是一个 2X3 的数组

In [ ]:
arr3d[1]

In [ ]:
old_values = arr3d[0].copy()

In [ ]:
arr3d[0] = 42

In [ ]:
arr3d

In [ ]:
arr3d[0] = old_values

In [ ]:
arr3d

In [ ]:
arr3d[1, 0] # 返回的是一个一维数组

### 上面的表达式可以分解为下面两步：

In [ ]:
x = arr3d[1]

In [ ]:
x

In [ ]:
x[0]

### Indexing with slices
### 数组的切片索引

In [ ]:
arr

In [ ]:
arr[5:8] = 64

In [ ]:
arr[1:6]

In [ ]:
arr2d

In [ ]:
arr2d[:2] # 数组沿着轴 0 进行了切片，表达式 arr2d[:2]的含义为选择 arr2d 的前两“行”

In [ ]:
arr2d[:2, 1:]

In [ ]:
arr2d[1, :2]

In [ ]:
arr2d[:2, 2]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:2, 1:] = 0
arr2d

![](http://ww3.sinaimg.cn/large/006y8mN6ly1g6aqn1fvvqj30hb0khgpb.jpg)

### Boolean Indexing
### 布尔索引

#### 假设我们的数据都在数组中，并且数组中的数据是一些存在重复的人名。我会使用 numpy.random 中的 randn 函数来生成一些随机正态分布的数据：

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) # 包含了重复值的一维数组
data = np.random.randn(7, 4) # 7X4 的二维数组

In [ ]:
names

In [ ]:
data

### 假设每个人名都和 data 数组中的一行相对应，并且我们想要选中所有‘Bob’对应的行。与数学操作类似，数组的比较操作(比如 ==) 也是可以向量化的。因此比较 names 数组和字符串 'Bob' 会产生一个布尔值数组。

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob'] # 在索引数组时可以传入布尔值数组。

In [ ]:
data[names == 'Bob', 2:] # 在上一个结果的基础上，取 2：

In [ ]:
data[names == 'Bob', 3]  # 在上上一个结果的基础上，取 3

### 为了选择除了'Bob'以外的其他数据，你可以使用 != 或在条件表达式前使用 ~ 对条件取反

In [ ]:
names != 'Bob'

In [ ]:
data[~(names == 'Bob')]

### ~ 符号可以在你想要对一个通用条件进行取反时使用：

In [ ]:
cond = names == 'Bob'
data[~cond]

In [ ]:
mask = (names == 'Bob') | (names == 'Will')

In [ ]:
mask

In [ ]:
data[mask]

### 使用布尔值索引选择数据时，总是生成数据的拷贝，即使返回的数组并没有任何变化。

### Python 的关键字 and 和 or 对布尔值数组并没有用，请使用 & 和 | 来代替。

In [ ]:
data[data < 0] = 0

In [ ]:
data

In [ ]:
data[names != 'Joe'] = 7

In [ ]:
data

### Fancy Indexing
### 神奇索引

In [ ]:
arr = np.empty((8, 4)) # 创建一个 8X4 的空的二维数组
arr

In [ ]:
for i in range(8):
    arr[i] = i
arr

### 为了选出一个符合特定顺序的子集，可以简单的通过床底一个包含指明所需顺序的列表或数组来完成。

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]  # 如果是负的索引，将从尾部进行选择

In [ ]:
arr = np.arange(32).reshape((8, 4))

In [ ]:
arr

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # 元素(1,0)(5,3)(7,1)(2,2)被选中

In [ ]:
arr[[1, 5, 7, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

### Transposing Arrays and Swapping Axes
### 数组转置和换轴

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

### 转置是一种特殊的数据重组形式，可以返回底层数据的视图而不是需要复制任何内容。数组拥有 transpose 方法。也有特殊的 T 属性：

In [ ]:
arr.T

### 当进行矩阵计算时，你可能会经常进行特定的操作。比如，当计算[矩阵内积](https://blog.csdn.net/CareChere/article/details/78496752)会使用 np.dot

In [3]:
arr = np.random.randn(6, 3)

In [4]:
arr

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934],
       [ 0.0929,  0.2817,  0.769 ],
       [ 1.2464,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  1.3529],
       [ 0.8864, -2.0016, -0.3718]])

In [5]:
arr.T

array([[-0.2047, -0.5557,  0.0929,  1.2464,  0.275 ,  0.8864],
       [ 0.4789,  1.9658,  0.2817,  1.0072,  0.2289, -2.0016],
       [-0.5194,  1.3934,  0.769 , -1.2962,  1.3529, -0.3718]])

In [6]:
np.dot(arr.T, arr)

array([[ 2.7744, -1.6203, -2.1698],
       [-1.6203,  9.2464,  2.4555],
       [-2.1698,  2.4555,  6.4516]])

### 对于更高维度的数组，[transpose](https://blog.csdn.net/u012762410/article/details/78912667) 方法可以接受包含轴编号的元组，用于置换轴

In [7]:
arr = np.arange(16).reshape((2, 2, 4))

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
np.ndim(arr)

3

In [11]:
np.shape(arr)

(2, 2, 4)

In [16]:
firstIndex = secondIndex = thirdIndex = 0

for first in arr:
    for second in first:
        for third in second:
            print("arr[{0}][{1}][{2}] = {3} ".format(firstIndex,secondIndex,thirdIndex,third))
            thirdIndex = thirdIndex + 1
        secondIndex = secondIndex + 1
        thirdIndex =0
    firstIndex = firstIndex + 1
    secondIndex = 0

arr[0][0][0] = 0 
arr[0][0][1] = 1 
arr[0][0][2] = 2 
arr[0][0][3] = 3 
arr[0][1][0] = 4 
arr[0][1][1] = 5 
arr[0][1][2] = 6 
arr[0][1][3] = 7 
arr[1][0][0] = 8 
arr[1][0][1] = 9 
arr[1][0][2] = 10 
arr[1][0][3] = 11 
arr[1][1][0] = 12 
arr[1][1][1] = 13 
arr[1][1][2] = 14 
arr[1][1][3] = 15 


![](http://ww3.sinaimg.cn/large/006y8mN6ly1g6ayqh5lfgj30dw0dwaam.jpg)

In [9]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

![](http://ww3.sinaimg.cn/large/006y8mN6ly1g6ayr7c8vkj30dw0dw74u.jpg)

In [ ]:
arr
arr.swapaxes(1, 2)

## Universal Functions: Fast Element-Wise Array Functions

In [ ]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y)

In [ ]:
arr = np.random.randn(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

In [ ]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

## Array-Oriented Programming with Arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close('all')

### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

### Mathematical and Statistical Methods

In [ ]:
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(axis=0)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

### Methods for Boolean Arrays

In [ ]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = np.random.randn(6)
arr
arr.sort()
arr

In [ ]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and Other Set Logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File Input and Output with Arrays

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

## Linear Algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Pseudorandom Number Generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

In [ ]:
np.random.seed(1234)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)

## Example: Random Walks

In [ ]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [ ]:
plt.figure()

In [ ]:
plt.plot(walk[:100])

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating Many Random Walks at Once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))

## Conclusion